### ISSUE TITLE
Discussion: auto-suggesting channels based on interests

### ISSUE THREAD

**Issue by cjdenio** [hackclub/clippy#22]
What if Clippy could ask for new members' interests, then suggest channels based on those interests? Sort of like this:

**Clippy**
> Welcome to the community! What kind of things are you in to? Just drop the answer in the chat! :arrow_down: 

**Person**
> Hmm... I'd say I like building mobile apps!

**Clippy**
> ![image](https://user-images.githubusercontent.com/34525547/94928302-7be05300-0491-11eb-82c5-f758a3533d41.png)

I'd be happy to start implementing this if y'all think it's a good idea!

**Comment by MatthewStanciu** [comment]
I'm totally down for something like this if you want to implement it. I think we just need to be very careful about how we word it, because I can totally see someone either totally new to coding or for who English isn't their first language being confused and typing the same responses that we see in #welcome-committee ("I am into a great fantastic community where I can learn and grow with like-minded people!")

**Comment by MatthewStanciu** [comment]
But if you're feeling inspired, I think you should go for it, and we can solve any problems that may come up as they come up
